spring:
  application:
    name: api-gateway

  main:
    web-application-type: reactive

  cloud:
    config:
      enabled: false

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}

server:
  port: 7777
