spring:
  application:
    name: api-gateway

  main:
    web-application-type: reactive

  cloud:
    config:
      enabled: false
    gateway:
      discovery:
        locator:
          enabled: true
      routes :
      - id : ms-order
        uri : http://localhost:8080
        predicates :
          - Path= /orders/**
        filters:
          - RewritePath= /orders/?(?<segment>.*), /${segment}




eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}


server:
  port: 7777