spring:
  application:
    name: ms-paymnet
  datasource:
    url: jdbc:postgresql://localhost:5432/payment_db

    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update



server:
  port: 8082