spring:
  application:
    name: ms-payment
  datasource:
    url: jdbc:postgresql://localhost:5432/product_db?currentSchema=payment_schema

    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
      default_schema: payment_schema



server:
  port: 8082

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}