spring:
  application:
    name: ms-product
  datasource:
    url: jdbc:postgresql://localhost:5432/product_db?currentSchema=product_schema
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
      default_schema: product_schema


server:
  port: 8081

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}